#$schema: https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: djdevops-app-acr
  annotations:
    argocd/app-name: djdevops-app
  tags:
    - helm
spec:
  type: config-repo
  lifecycle: development
  owner: demo-team
  dependsOn:
    - component:default/djdevops-app